// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_1ezZkePv7l-C7VrJTCL-ISWBsnNkDjo',
    appId: '1:249741549405:web:754e48144c226668f0d2b4',
    messagingSenderId: '249741549405',
    projectId: 'myfirstproject-c37e0',
    authDomain: 'myfirstproject-c37e0.firebaseapp.com',
    storageBucket: 'myfirstproject-c37e0.appspot.com',
    measurementId: 'G-RB2V9PBJBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx3KqjvQwVrouFg_X6xC-igGHKuGk0xdM',
    appId: '1:249741549405:android:e8c56a04e071fd5df0d2b4',
    messagingSenderId: '249741549405',
    projectId: 'myfirstproject-c37e0',
    storageBucket: 'myfirstproject-c37e0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUyD1oAW4saU4KFtCpw5R5mZhg2qEhmcs',
    appId: '1:249741549405:ios:617d472a343ec54cf0d2b4',
    messagingSenderId: '249741549405',
    projectId: 'myfirstproject-c37e0',
    storageBucket: 'myfirstproject-c37e0.appspot.com',
    iosBundleId: 'com.example.loginRegistration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUyD1oAW4saU4KFtCpw5R5mZhg2qEhmcs',
    appId: '1:249741549405:ios:617d472a343ec54cf0d2b4',
    messagingSenderId: '249741549405',
    projectId: 'myfirstproject-c37e0',
    storageBucket: 'myfirstproject-c37e0.appspot.com',
    iosBundleId: 'com.example.loginRegistration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_1ezZkePv7l-C7VrJTCL-ISWBsnNkDjo',
    appId: '1:249741549405:web:0c13d981328edc86f0d2b4',
    messagingSenderId: '249741549405',
    projectId: 'myfirstproject-c37e0',
    authDomain: 'myfirstproject-c37e0.firebaseapp.com',
    storageBucket: 'myfirstproject-c37e0.appspot.com',
    measurementId: 'G-NPRGM82J13',
  );
}
